version: '3'
services:
  currency-conversion-service:
    image: tomek371240/currency-conversion-service:5.0
    networks:
      - springcloud-overlay
    command: tail -f /dev/null
    ports:
      - "8100:8100"

networks:
  springcloud-overlay:
    external:
      name: springcloud-overlay