version: '3'
services:
  netflix-eureka-naming-server:
    image:  tomek371240/netflix-eureka-naming-server:5.0
    networks:
      - springcloud-overlay
  repository-server:
    image: tomek371240/repository:1.0
    networks:
      - springcloud-overlay
  authorization-server:
    image: tomek371240/authorization:5.0
    networks:
      - springcloud-overlay
    depends_on:
      - netflix-eureka-naming-server
  netflix-zuul-api-gateway-server:
    image: tomek371240/netflix-authorization-api-gateway-server:5.0
    networks:
      - springcloud-overlay
    ports:
      - "8765:8765"
  nginx:
    image: tomek371240/nginx:5.0
    networks:
      - springcloud-overlay
    ports:
      - 80:80
networks:
  springcloud-overlay:
    external:
      name: springcloud-overlay
#docker network create -d overlay springcloud-overlay
#docker stack deploy -c pre-containers.yml pre_stack
#docker stack deploy -c docker-compose.yml first_stack
#docker stack deploy -c secendary-container.yml sec_stack
