version: '3'
services:
  netflix-eureka-naming-server:
    image:  tomek371240/netflix-eureka-naming-server:5.0
    networks:
      - springcloud-overlay
  limits-service:
    image: tomek371240/limit-service:5.0
    networks:
      - springcloud-overlay
    ports:
      - "8080:8080"
  repository-server:
    image: tomek371240/repository:1.0
    networks:
      - springcloud-overlay
  nginx:
    image: tomek371240/nginx:5.0
    networks:
      - springcloud-overlay
    ports:
      - 80:80
  #    command: nginx -g "daemon off"
  #    command: tail -f /dev/null1

  authorization-server:
    image: tomek371240/authorization:5.0
    networks:
      - springcloud-overlay
    depends_on:
      - netflix-eureka-naming-server
  currency-exchange-service:
    image: tomek371240/currency-exchange-service:5.0
    networks:
      - springcloud-overlay
  #    ports:
  #      - "8000:8000"
  currency-conversion-service:
    image: tomek371240/currency-conversion-service:5.0
    networks:
      - springcloud-overlay
  #    ports:
  #      - "8100:8100"
  netflix-zuul-api-gateway-server:
    image: tomek371240/netflix-zuul-api-gateway-server:5.0
    networks:
      - springcloud-overlay
    ports:
      - "8765:8765"
networks:
  springcloud-overlay:
    external:
      name: springcloud-overlay
#docker network create -d overlay springcloud-overlay
#docker stack deploy -c pre-containers.yml pre_stack
#docker stack deploy -c docker-compose.yml first_stack
#docker stack deploy -c secendary-container.yml sec_stack
