version: "3"
services:
  postgres:
    image: postgres:latest
    ports:
      - "5431:5432"
    environment:
      - "POSTGRES_USER=docker"
      - "POSTGRES_PASSWORD=docker"
      - "POSTGRES_DB=docker"
    networks:
      - springcloud-overlay
  rabbitmq:
    image: rabbitmq:3.7.6-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - "TZ=@timezone@"
    networks:
      - springcloud-overlay
  zipkin:
    image: openzipkin/zipkin:2.10.2
    environment:
      - "TZ=@timezone@"
      - "RABBIT_URI=amqp://guest:guest@rabbitmq:5672"
    networks:
      - springcloud-overlay
  spring-cloud-config-server:
    image: tomek371240/config-server:5.0
    networks:
      - springcloud-overlay
    ports:
      - "8888:8888"
  limits-service:
    image: tomek371240/limit-service:5.0
    networks:
      - springcloud-overlay
    ports:
      - "8080:8080"
    depends_on:
      - spring-cloud-config-server
  netflix-eureka-naming-server:
    image:  tomek371240/netflix-eureka-naming-server:5.0
    networks:
      - springcloud-overlay

networks:
  springcloud-overlay:
    external:
      name: springcloud-overlay
