version: '3'
services:
  netflix-zuul-api-gateway-server:
    image: tomek371240/netflix-zuul-api-gateway-server:4.0
    networks:
      - springcloud-overlay
    ports:
      - "8765:8765"
networks:
  springcloud-overlay:
    external:
      name: springcloud-overlay