version: "3"
services:
  nginx:
    image: tomek371240/nginx:3.1
    networks:
      - springcloud-overlay
    ports:
      - 80:80
#    command: nginx -g "daemon off"
#    command: tail -f /dev/null
networks:
  springcloud-overlay:
    external:
      name: springcloud-overlay

#  docker stack deploy -c docker-compose.yml nginx3_stack
