version: '3'
services:
  authorization-server:
    image: tomek371240/authorization:1.4
    networks:
      - springcloud-overlay
#    ports:
#      - "9000:9000"
networks:
  springcloud-overlay:
    external:
      name: springcloud-overlay
