version: '3'
services:
  spring-cloud-config-server:
    image: tomek371240/config-server:5.0
    networks:
      - springcloud-overlay
    ports:
      - "8888:8888"
networks:
  springcloud-overlay:
    external:
      name: springcloud-overlay
