version: '3'
services:
  limits-service:
    image: tomek371240/limit-service:5.0
    networks:
      - springcloud-overlay
    ports:
      - "8080:8080"
networks:
  springcloud-overlay:
    external:
      name: springcloud-overlay
