version: "3"
services:
  postgres:
    image: postgres:latest
    ports:
      - "5431:5432"
    environment:
      - "POSTGRES_USER=docker"
      - "POSTGRES_PASSWORD=docker"
      - "POSTGRES_DB=docker"
    networks:
      - springcloud-overlay

networks:
  springcloud-overlay:
    external:
      name: springcloud-overlay