version: '3'
services:
  report-server:
    image: tomek371240/report-service:1
    networks:
      - springcloud-overlay
networks:
  springcloud-overlay:
    external:
      name: springcloud-overlay
