version: "3"
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5430:5432"
    environment:
      - "POSTGRES_USER=docker"
      - "POSTGRES_PASSWORD=docker"
      - "POSTGRES_DB=docker"

